# Generated by Django 3.2.12 on 2022-03-28 17:31

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220328_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
