# Generated by Django 3.2.12 on 2022-03-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_category_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='default text', max_length=30),
            preserve_default=False,
        ),
    ]
