# Generated by Django 3.2.12 on 2022-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
